image: fjaeger123/java-dev-container:1.0.1

ports:
  - port: 2900
    onOpen: open-preview
tasks:
  - name: startjira
    command: atlas-run-standalone --product jira --jvmargs "-DdisableJiraEmail=false -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n"